// ── Program data: seeds the editable program on first run ──────────────
// Edit via the app (pencil icon); "Restore default program" re-loads this.

const PROGRAM_VERSION = 5;
const PROGRAM_START = '2026-07-06'; // Monday, week 1

function yt(q) {
  return 'https://www.youtube.com/results?search_query=' + encodeURIComponent(q);
}

const DEFAULT_PROGRAM = {
  version: PROGRAM_VERSION,
  name: 'Hybrid Block — Jul 6 to Aug 2',
  workouts: [
    {
      id: 'push',
      name: 'Push',
      where: 'Lifetime',
      icon: 'bench',
      painTracked: false,
      exercises: [
        { id: 'bench',      name: 'Barbell Bench Press',     sets: 4, reps: '6–8',     rest: 180, art: 'bench',      loc: 'Lifetime',
          tip: 'Shoulder blades pinched, feet planted. Bar to mid-chest, drive up and slightly back. Top sets at RPE 8 — heavy but every rep clean. No failure without a spotter or safeties.',
          video: yt('barbell bench press form') },
        { id: 'ohp',        name: 'Machine Shoulder Press',   sets: 3, reps: '6–8',     rest: 120, art: 'machinepress', loc: 'Lifetime',
          tip: 'Ribs down, drive to full lockout. The machine makes near-failure safe — take the last set to RPE 9.',
          video: yt('machine shoulder press form') },
        { id: 'incline',    name: 'Incline Press Machine',    sets: 3, reps: '6–8',     rest: 120, art: 'incline',    loc: 'Lifetime',
          tip: 'Plate-loaded incline at Lifetime. Upper chest — control the negative, drive hard. Last set near failure.',
          video: yt('incline chest press machine form') },
        { id: 'lateral',    name: 'Cable / Machine Lateral Raise', sets: 3, reps: '8–10', rest: 90, art: 'lateral',  loc: 'Lifetime',
          tip: 'Machine or single-arm cable. Lead with the elbow — 8–10 here because heavy swinging laterals just become traps.',
          video: yt('cable lateral raise form') },
        { id: 'pushdown',   name: 'Triceps Rope Pushdown',    sets: 3, reps: '8–10',    rest: 90,  art: 'pushdown',   loc: 'Lifetime',
          tip: 'Elbows pinned to your sides. Split the rope at the bottom and squeeze.',
          video: yt('triceps rope pushdown form') },
        { id: 'cablecrunch', name: 'Cable Crunch',            sets: 3, reps: '12',      rest: 60,  art: 'cablecrunch', loc: 'Lifetime', core: true,
          tip: 'Kneel, hips stay still — crunch ribs toward pelvis. Flex the abs, don’t pull with arms.',
          video: yt('kneeling cable crunch form') },
        { id: 'birddog',    name: 'Bird Dog',                 sets: 2, reps: '8/side',  rest: 45,  art: 'birddog',    loc: 'Lifetime', core: true,
          tip: 'Your low-back rebuild staple. Slow, 2-sec pause, hips stay level — pretend a cup of water is on your back.',
          video: yt('bird dog exercise McGill') },
      ],
    },
    {
      id: 'pull',
      name: 'Pull',
      where: 'Lifetime',
      icon: 'pullup',
      painTracked: false,
      exercises: [
        { id: 'pullup',     name: 'Lat Pulldown / Weighted Pull-Up', sets: 4, reps: '6–8', rest: 150, art: 'pullup',   loc: 'Lifetime',
          tip: 'Pulldown as the machine default — full stretch at the top, chest up, elbows down. Swap in weighted pull-ups whenever you feel like it.',
          video: yt('lat pulldown form') },
        { id: 'chestrow',   name: 'Chest-Supported Machine Row', sets: 3, reps: '6–8',  rest: 120, art: 'chestrow',   loc: 'Lifetime',
          tip: 'Chest glued to the pad — zero low-back load. Squeeze the mid-back; last set RPE 9 is fair game.',
          video: yt('chest supported machine row form') },
        { id: 'facepull',   name: 'Face Pull',                sets: 3, reps: '12',      rest: 60,  art: 'facepull',   loc: 'Lifetime',
          tip: 'Stays at 12 on purpose — it’s shoulder insurance for benching and hockey, not an ego lift. Rope to eyebrows, thumbs back.',
          video: yt('cable face pull form') },
        { id: 'curl',       name: 'Cable / Machine Curl',     sets: 3, reps: '8–10',    rest: 90,  art: 'curl',       loc: 'Lifetime',
          tip: 'Cable EZ-bar or preacher machine — constant tension, no swing. Last set near failure.',
          video: yt('cable curl form') },
        { id: 'backext',    name: '45° Back Extension',       sets: 3, reps: '12',      rest: 60,  art: 'backext',    loc: 'Lifetime', core: true,
          tip: 'THE low-back strengthener. Bodyweight first, add a light plate when smooth. Squeeze glutes at the top, never jerk.',
          video: yt('45 degree back extension form') },
        { id: 'pallof',     name: 'Pallof Press',             sets: 2, reps: '10/side', rest: 45,  art: 'pallof',     loc: 'Lifetime', core: true,
          tip: 'Anti-rotation: press out slow, resist the cable twisting you. Ribs stacked over hips.',
          video: yt('pallof press form') },
      ],
    },
    {
      id: 'legs',
      name: 'Legs',
      where: 'Garage → Lifetime',
      icon: 'squat',
      painTracked: true,
      warmup: true,
      exercises: [
        { id: 'squat',      name: 'Back Squat',               sets: 4, reps: '5',       rest: 180, art: 'squat',      loc: 'Garage',
          tip: 'THE progression lift. Wk1 ≈ 50–60% of pre-injury weight, every rep smooth. Pain over 2/10 → box squat, tempo squat, front squat, or goblet — any of them still counts.',
          video: yt('high bar back squat form') },
        { id: 'rdl',        name: 'Romanian Deadlift',        sets: 3, reps: '8',       rest: 150, art: 'rdl',        loc: 'Garage',
          tip: 'Patterning, not PRs. Push hips back, feel hamstrings stretch, spine stays locked neutral. Form breaks = set over.',
          video: yt('romanian deadlift form') },
        { id: 'legext',     name: 'Leg Extension',            sets: 3, reps: '8–10',    rest: 90,  art: 'legext',     loc: 'Lifetime',
          tip: 'Pure quad, zero spine — this is your heavy quad slot while the squat rehabs. 2-sec squeeze at the top, control the way down, last set near failure.',
          video: yt('leg extension machine form') },
        { id: 'legcurl',    name: 'Seated Leg Curl',          sets: 3, reps: '8–10',    rest: 90,  art: 'legcurl',    loc: 'Lifetime',
          tip: 'Heavy but controlled — hamstrings grow on the way back up, and they protect your back and knees on the ice.',
          video: yt('seated leg curl form') },
        { id: 'calf',       name: 'Machine Calf Raise',       sets: 3, reps: '8–10',    rest: 60,  art: 'calf',       loc: 'Lifetime',
          tip: 'Standing machine or calf sled. 2-sec pause in the bottom stretch — doubles as ankle mobility for the duck-foot fix.',
          video: yt('machine standing calf raise form') },
        { id: 'abmachine',  name: 'Ab Crunch Machine',        sets: 2, reps: '12',      rest: 60,  art: 'abmachine',  loc: 'Lifetime', core: true,
          tip: 'Exhale as you crunch, slow return. Weight you can control, not maximal.',
          video: yt('ab crunch machine form') },
        { id: 'sideplank',  name: 'Side Plank',               sets: 2, reps: '30s/side', rest: 45, art: 'sideplank', loc: 'Lifetime', core: true,
          tip: 'McGill staple for your back. Straight line ankle–hip–shoulder; don’t let the hip sag.',
          video: yt('side plank form') },
      ],
    },
    {
      id: 'oly',
      name: 'Oly + Explosive',
      where: 'Garage',
      icon: 'snatch',
      painTracked: true,
      warmup: true,
      exercises: [
        { id: 'drills',     name: 'Empty-Bar Snatch Drills',  sets: 1, reps: '5 min',   rest: 0,   art: 'bar',        loc: 'Garage',
          tip: 'Snatch-grip RDL → high pull → muscle snatch → overhead squat, 5 reps each. This is the tune-up — don’t skip it.',
          video: yt('burgener warm up snatch') },
        { id: 'snatch',     name: 'Power Snatch',             sets: 6, reps: '2',       rest: 120, art: 'snatch',     loc: 'Garage',
          tip: 'Weeks 1–2 from the hang, weeks 3–4 from the floor. Crisp beats heavy every single week. Bar stays close, punch the lockout.',
          video: yt('power snatch technique') },
        { id: 'cleanjerk',  name: 'Power Clean + Push Jerk',  sets: 5, reps: '2+1',     rest: 150, art: 'cleanjerk',  loc: 'Garage',
          tip: 'Two cleans, one jerk per set. Bar speed is the judge — the moment it slows, stop adding weight.',
          video: yt('power clean push jerk technique') },
        { id: 'frontsquat', name: 'Front Squat',              sets: 3, reps: '3–5',     rest: 120, art: 'frontsquat', loc: 'Garage',
          tip: 'Light-moderate — position work, and it saves your legs for Saturday squats. Elbows high the whole rep.',
          video: yt('front squat form') },
        { id: 'boxjump',    name: 'Box / Broad Jump',         sets: 3, reps: '3',       rest: 90,  art: 'boxjump',    loc: 'Garage',
          tip: 'Full recovery between sets — this is power, not conditioning. Land quiet like a cat.',
          video: yt('box jump technique') },
        { id: 'mcgill',     name: 'McGill Big-3 Circuit',     sets: 2, reps: '1 round', rest: 45,  art: 'curlup',     loc: 'Garage', core: true,
          tip: 'Per round: bird dog ×8/side, side plank 30s/side, curl-up ×8. Done at home — no gym trip needed.',
          video: yt('McGill big 3 exercises') },
      ],
    },
  ],
};

// ── Weekly schedule ─────────────────────────────────────────────────────
// day: 0=Mon … 6=Sun
const SCHEDULE = {
  week1: [
    { day: 0, workout: 'push', label: 'Push', where: 'Lifetime' },
    { day: 1, workout: 'pull', label: 'Pull', where: 'Lifetime' },
    { day: 2, workout: 'legs', label: 'Legs', where: 'Garage → Lifetime' },
    { day: 3, workout: null,   label: 'Rest + ankle/hip mobility', where: 'Home' },
    { day: 4, workout: 'oly',  label: 'Oly + Explosive', where: 'Garage' },
    { day: 5, workout: null,   label: 'Optional zone-2 or full rest', where: '—' },
    { day: 6, workout: null,   label: 'Sunday mobility session', where: 'Home' },
  ],
  week2plus: [
    { day: 0, workout: 'push', label: 'Push', where: 'Lifetime' },
    { day: 1, workout: null,   label: 'Hockey (evening) — morning routine only', where: 'Rink' },
    { day: 2, workout: null,   label: 'Dryland + hockey — full day, nothing else', where: 'Rink' },
    { day: 3, workout: 'pull', label: 'Pull (daytime) + hockey (evening)', where: 'Lifetime' },
    { day: 4, workout: 'oly',  label: 'Oly + Explosive', where: 'Garage' },
    { day: 5, workout: 'legs', label: 'Legs', where: 'Garage → Lifetime' },
    { day: 6, workout: null,   label: 'Sunday mobility session', where: 'Home' },
  ],
};

const PROGRESSION = {
  1: { label: 'Week 1 — set the bar',
       upper: 'You’re not detrained — work up to top sets at RPE 8 (1–2 reps in reserve) and log your numbers.',
       lower: 'Two speeds: squat/RDL stay pain-gated (~60% pre-injury, every rep smooth); machines go straight to RPE 8.',
       oly:   'Hang power variations. Load follows crispness — the bar can climb as long as technique stays sharp.' },
  2: { label: 'Week 2 — build',
       upper: 'Add 5–10 lb wherever week 1 moved fast. Top sets RPE 8–9.',
       lower: 'Squat +10–20 lb only if week 1 was pain-free. Machines keep climbing.',
       oly:   'Lifts move to the floor. Heavier crisp doubles.' },
  3: { label: 'Week 3 — heaviest',
       upper: 'Top sets RPE 9 (0–1 in reserve). Heavy, not grinding — bar speed stays honest.',
       lower: 'Squat +10–20 lb if the back stays quiet, cap at RPE 8. Machines: RPE 9.',
       oly:   'Build to a daily-max power snatch + power clean single — only if the back has been silent 2 straight weeks.' },
  4: { label: 'Week 4 — consolidate',
       upper: 'Match week 3 loads with better speed, or cut volume 30% if hockey has you run down.',
       lower: 'Hold week 3 squat weight and own it.',
       oly:   'If positions + back both feel good: test light full (squat) snatch and clean. The “I’m back” checkpoint.' },
};

const GUARDRAILS = [
  'Pain is the gate: 0–2/10 during a set → proceed. Anything sharper → drop weight or swap the variation that day.',
  'Grinding is an upper-body and machine privilege. Anything loading the spine (squat, RDL, Oly pulls) stays crisp — no ugly reps there, no matter how good the back feels.',
  'Squat substitutes, in order: box squat → tempo squat (3s down) → front squat → goblet squat.',
  'RDLs are patterning, not PRs. Form breaks = set over.',
  'Oly pulls stay at technique weight weeks 1–2 no matter how easy they feel.',
  'No heavy bending in the first ~30 min after waking — do the morning routine instead.',
];

const ROUTINES = [
  {
    id: 'warmup', name: 'Garage Lower-Body Warm-Up', when: 'Before every Legs + Oly session · ~6 min',
    items: [
      { name: 'Cat-Cow', dose: '× 10', art: 'catcow',
        tip: 'Move segment by segment — round the whole spine up like an angry cat, then let the belly drop. Wakes the back gently before load.',
        video: yt('cat cow exercise') },
      { name: 'Ankle Rocks', dose: '× 10/side', art: 'anklerock',
        tip: 'Half-kneeling, drive the knee out over the toes with the heel glued down. This is THE ankle-mobility money move.',
        video: yt('knee over toe ankle mobility drill') },
      { name: 'Glute Bridge', dose: '× 12 · 2-sec squeeze', art: 'glutebridge',
        tip: 'Push through the heels, squeeze the glutes hard at the top. Don’t arch the low back to get higher.',
        video: yt('glute bridge form') },
      { name: 'Dead Bug', dose: '× 8/side', art: 'deadbug',
        tip: 'Low back pressed flat into the floor the entire time. Opposite arm and leg reach away slow.',
        video: yt('dead bug exercise form') },
      { name: 'Bird Dog', dose: '× 6/side · 2-sec pause', art: 'birddog',
        tip: 'Hips stay level — imagine balancing a cup of water on your back.',
        video: yt('bird dog exercise McGill') },
      { name: 'Goblet Squat Ramp', dose: '× 10, then bar in 3s–5s', art: 'deepsquat',
        tip: 'Sit down between the heels, chest tall. Then ramp the empty bar up in small sets — never jump straight to work weight.',
        video: yt('goblet squat form') },
    ],
  },
  {
    id: 'morning', name: 'Morning Routine', when: 'Every day · ~8 min · unsticks back + ankles',
    items: [
      { name: 'Cat-Cow', dose: '× 10 slow', art: 'catcow',
        tip: 'First movement of the day — keep it easy and smooth, no forcing end range while the discs are still waking up.',
        video: yt('cat cow exercise') },
      { name: 'Ankle Rocks', dose: '× 10/side', art: 'anklerock',
        tip: 'Knee tracks out over the toes, heel stays down. Daily reps here are what straighten out the duck-foot walk.',
        video: yt('knee over toe ankle mobility drill') },
      { name: 'Half-Kneeling Hip Flexor Stretch', dose: '30s/side', art: 'hipflexor',
        tip: 'Squeeze the back-leg glute and tuck the pelvis under — feel the front of the hip, never the low back.',
        video: yt('half kneeling hip flexor stretch') },
      { name: 'Glute Bridge', dose: '× 12 · 2-sec hold', art: 'glutebridge',
        tip: 'Wakes the glutes up so they, not your low back, run the show all day.',
        video: yt('glute bridge form') },
      { name: 'Bird Dog', dose: '× 6/side', art: 'birddog',
        tip: 'Slow and level. Morning bird dogs are your back’s daily maintenance dose.',
        video: yt('bird dog exercise McGill') },
      { name: 'Supported Deep Squat Hold', dose: '30s', art: 'deepsquat',
        tip: 'Hold the rack or a doorframe, heels down, sit deep and breathe into the bottom.',
        video: yt('deep squat hold mobility') },
      { name: 'Overhead Reach + Side Bend', dose: '× 5/side', art: 'reach',
        tip: 'Reach tall, then bend sideways like you’re sliding a hand down a wall. Opens the ribs and T-spine.',
        video: yt('standing overhead side bend stretch') },
    ],
  },
  {
    id: 'night', name: 'Night Routine', when: 'Every day · ~10 min · decompress + downshift',
    items: [
      { name: 'Knees-to-Chest Rock', dose: '60s', art: 'kneeschest',
        tip: 'Hug the knees and rock gently — decompresses the low back after the day’s loading.',
        video: yt('knees to chest stretch low back') },
      { name: 'Figure-4 Stretch', dose: '45s/side', art: 'figure4',
        tip: 'Ankle over the opposite knee, pull the leg toward you. Deep glute stretch — breathe into it, don’t fight it.',
        video: yt('supine figure 4 stretch') },
      { name: 'Hamstring Stretch w/ Strap', dose: '45s/side', art: 'hamstring',
        tip: 'Leg up with a strap or towel, knee soft, low back stays on the floor. Stretch, don’t yank.',
        video: yt('lying hamstring stretch with strap') },
      { name: 'Pigeon', dose: '60s/side', art: 'pigeon',
        tip: 'Front shin angled, hips square, fold forward slowly. The reclined version counts on tired nights.',
        video: yt('pigeon pose stretch tutorial') },
      { name: 'Open-Book', dose: '× 8/side', art: 'openbook',
        tip: 'Side-lying with knees stacked — rotate the top arm open and follow the hand with your eyes.',
        video: yt('open book thoracic rotation') },
      { name: 'Child’s Pose', dose: '90s', art: 'childpose',
        tip: 'Knees wide, arms long, slow nasal breaths with long exhales. This is the off switch for sleep.',
        video: yt('childs pose breathing stretch') },
    ],
  },
  {
    id: 'sunday', name: 'Sunday Mobility Session', when: 'Sundays · ~25 min · the duck-foot fixer',
    items: [
      { sec: 'Ankles', name: 'Wall Calf Stretch', dose: '60s/side', art: 'calfstretch',
        tip: 'Back knee straight, heel glued down, lean into the wall.',
        video: yt('wall calf stretch gastrocnemius') },
      { sec: 'Ankles', name: 'Soleus Stretch', dose: '60s/side', art: 'calfstretch',
        tip: 'Same setup but bend the back knee — hits the deeper calf muscle that actually limits your ankle.',
        video: yt('soleus stretch bent knee wall') },
      { sec: 'Ankles', name: 'Knee-Over-Toe Ankle Rocks', dose: '× 15/side', art: 'anklerock',
        tip: 'Bigger dose than the daily version — chase a little more range each week.',
        video: yt('knee over toe ankle mobility drill') },
      { sec: 'Ankles', name: 'Tibialis Raises', dose: '2 × 15', art: 'tibraise',
        tip: 'Lean back against a wall, lift the toes as high as you can. Shin strength = ankle control for the duck-foot fix.',
        video: yt('tibialis raise wall lean') },
      { sec: 'Hips', name: '90/90 Transitions', dose: '× 10 slow', art: 'ninety',
        tip: 'Both legs at 90°, rotate side to side — no hands if you can. Hip internal rotation is the other half of the duck-foot fix.',
        video: yt('90 90 hip switch mobility') },
      { sec: 'Hips', name: '90/90 Internal-Rotation Lean', dose: '45s/side', art: 'ninety',
        tip: 'Lean your chest toward the back leg’s shin to bias internal rotation. It’ll feel awkward — that’s the point.',
        video: yt('90 90 internal rotation stretch') },
      { sec: 'Hips', name: 'Adductor Rockback', dose: '× 10/side', art: 'adductor',
        tip: 'One leg out to the side, rock the hips straight back with a neutral spine. Groin stretch for skating stride.',
        video: yt('adductor rockback stretch') },
      { sec: 'Hips', name: 'Half-Kneeling Hip Flexor', dose: '45s/side', art: 'hipflexor',
        tip: 'Longer hold than the morning version — glute squeezed, pelvis tucked.',
        video: yt('half kneeling hip flexor stretch') },
      { sec: 'Spine', name: 'Cat-Cow', dose: '× 10', art: 'catcow',
        tip: 'Smooth and segmented.',
        video: yt('cat cow exercise') },
      { sec: 'Spine', name: 'Thread the Needle', dose: '× 8/side', art: 'openbook',
        tip: 'From all fours, slide one arm under and through, following the hand with your eyes. T-spine rotation for jerks and shooting.',
        video: yt('thread the needle stretch') },
      { sec: 'Spine', name: 'Wall Slides', dose: '× 10', art: 'wallslide',
        tip: 'Back, elbows and wrists on the wall; slide up without the ribs flaring. Direct overhead prep for the jerk.',
        video: yt('wall slides shoulder mobility') },
      { sec: 'Spine', name: 'Rack Lat Stretch', dose: '45s', art: 'latstretch',
        tip: 'Grab the rack, sit the hips back, let the armpit sink toward the floor. Opens the overhead position.',
        video: yt('lat stretch on squat rack') },
      { sec: 'Finish', name: 'Deep Squat Hold', dose: '3 × 30s', art: 'deepsquat',
        tip: 'Breathe at the bottom. This is the position your snatch lives in — make it home.',
        video: yt('deep squat hold mobility') },
      { sec: 'Finish', name: 'Bird Dog', dose: '× 8/side', art: 'birddog',
        tip: 'End every mobility session the way the back likes: stable and level.',
        video: yt('bird dog exercise McGill') },
    ],
  },
];

const WALKING_CUE = 'Duck-foot walking cue: think “kneecaps point forward” and soften the knees. Don’t force the toes inward — the ankle + hip work is what actually changes it.';
