// ── Program data: seeds the editable program on first run ──────────────
// Edit via the app (pencil icon); "Restore default program" re-loads this.

const PROGRAM_VERSION = 1;
const PROGRAM_START = '2026-07-06'; // Monday, week 1

function yt(q) {
  return 'https://www.youtube.com/results?search_query=' + encodeURIComponent(q);
}

const DEFAULT_PROGRAM = {
  version: PROGRAM_VERSION,
  name: 'Hybrid Block — Jul 6 to Aug 2',
  workouts: [
    {
      id: 'push',
      name: 'Push',
      where: 'Lifetime',
      icon: 'bench',
      painTracked: false,
      exercises: [
        { id: 'bench',      name: 'Barbell Bench Press',     sets: 4, reps: '5–8',      art: 'bench',      loc: 'Lifetime',
          tip: 'Shoulder blades pinched, feet planted. Bar to mid-chest, drive up and slightly back. Wk1: find a solid RPE 7 (3 reps left in the tank).',
          video: yt('barbell bench press form') },
        { id: 'ohp',        name: 'Seated DB Overhead Press', sets: 3, reps: '8–10',    art: 'ohp',        loc: 'Lifetime',
          tip: 'Ribs down — don’t arch the low back to press. Full lockout overhead, control the way down.',
          video: yt('seated dumbbell overhead press form') },
        { id: 'incline',    name: 'Incline DB Press',         sets: 3, reps: '8–12',    art: 'incline',    loc: 'Lifetime',
          tip: 'Bench at 30–45°. Elbows about 45° from your body. Upper-chest builder — physique money.',
          video: yt('incline dumbbell press form') },
        { id: 'lateral',    name: 'Lateral Raise',            sets: 3, reps: '12–15',   art: 'lateral',    loc: 'Lifetime',
          tip: 'Lighter than you want. Lead with the elbows, slight forward lean, zero swing.',
          video: yt('dumbbell lateral raise form') },
        { id: 'pushdown',   name: 'Triceps Rope Pushdown',    sets: 3, reps: '10–12',   art: 'pushdown',   loc: 'Lifetime',
          tip: 'Elbows pinned to your sides. Split the rope at the bottom and squeeze.',
          video: yt('triceps rope pushdown form') },
        { id: 'cablecrunch', name: 'Cable Crunch',            sets: 3, reps: '12',      art: 'cablecrunch', loc: 'Lifetime', core: true,
          tip: 'Kneel, hips stay still — crunch ribs toward pelvis. Flex the abs, don’t pull with arms.',
          video: yt('kneeling cable crunch form') },
        { id: 'birddog',    name: 'Bird Dog',                 sets: 2, reps: '8/side',  art: 'birddog',    loc: 'Lifetime', core: true,
          tip: 'Your low-back rebuild staple. Slow, 2-sec pause, hips stay level — pretend a cup of water is on your back.',
          video: yt('bird dog exercise McGill') },
      ],
    },
    {
      id: 'pull',
      name: 'Pull',
      where: 'Lifetime',
      icon: 'pullup',
      painTracked: false,
      exercises: [
        { id: 'pullup',     name: 'Pull-Up / Lat Pulldown',   sets: 4, reps: '6–10',    art: 'pullup',     loc: 'Lifetime',
          tip: 'Pull-ups if you can get 6+ clean reps, otherwise pulldown. Full hang, chest to bar, no kipping.',
          video: yt('weighted pull up form') },
        { id: 'chestrow',   name: 'Chest-Supported Row',      sets: 3, reps: '8–10',    art: 'chestrow',   loc: 'Lifetime',
          tip: 'Chest glued to the pad the whole set — zero low-back load, which is the point right now.',
          video: yt('chest supported dumbbell row form') },
        { id: 'dbrow',      name: 'Single-Arm DB Row',        sets: 3, reps: '10–12',   art: 'dbrow',      loc: 'Lifetime',
          tip: 'Free hand and knee braced on the bench. Pull to your hip, not your armpit.',
          video: yt('single arm dumbbell row form') },
        { id: 'facepull',   name: 'Face Pull',                sets: 3, reps: '15',      art: 'facepull',   loc: 'Lifetime',
          tip: 'Rope to your eyebrows, thumbs pointing behind you. Shoulder health for benching and hockey.',
          video: yt('cable face pull form') },
        { id: 'curl',       name: 'EZ-Bar / DB Curl',         sets: 3, reps: '10–12',   art: 'curl',       loc: 'Lifetime',
          tip: 'Elbows stay at your sides. If you swing, it’s too heavy.',
          video: yt('ez bar curl form') },
        { id: 'backext',    name: '45° Back Extension',       sets: 3, reps: '12',      art: 'backext',    loc: 'Lifetime', core: true,
          tip: 'THE low-back strengthener. Bodyweight first, add a light plate when smooth. Squeeze glutes at the top, never jerk.',
          video: yt('45 degree back extension form') },
        { id: 'pallof',     name: 'Pallof Press',             sets: 2, reps: '10/side', art: 'pallof',     loc: 'Lifetime', core: true,
          tip: 'Anti-rotation: press out slow, resist the cable twisting you. Ribs stacked over hips.',
          video: yt('pallof press form') },
      ],
    },
    {
      id: 'legs',
      name: 'Legs',
      where: 'Garage → Lifetime',
      icon: 'squat',
      painTracked: true,
      warmup: true,
      exercises: [
        { id: 'squat',      name: 'Back Squat',               sets: 4, reps: '5',       art: 'squat',      loc: 'Garage',
          tip: 'THE progression lift. Wk1 ≈ 50–60% of pre-injury weight, every rep smooth. Pain over 2/10 → box squat, tempo squat, front squat, or goblet — any of them still counts.',
          video: yt('high bar back squat form') },
        { id: 'rdl',        name: 'Romanian Deadlift',        sets: 3, reps: '8',       art: 'rdl',        loc: 'Garage',
          tip: 'Patterning, not PRs. Push hips back, feel hamstrings stretch, spine stays locked neutral. Form breaks = set over.',
          video: yt('romanian deadlift form') },
        { id: 'legpress',   name: 'Leg Press',                sets: 3, reps: '10–12',   art: 'legpress',   loc: 'Lifetime',
          tip: 'Quad volume with no spinal load — perfect right now. Don’t let your low back round off the pad at the bottom.',
          video: yt('leg press form') },
        { id: 'legcurl',    name: 'Seated Leg Curl',          sets: 3, reps: '10–12',   art: 'legcurl',    loc: 'Lifetime',
          tip: 'Control the return — hamstrings grow on the way back up.',
          video: yt('seated leg curl form') },
        { id: 'calf',       name: 'Standing Calf Raise',      sets: 3, reps: '12–15',   art: 'calf',       loc: 'Lifetime',
          tip: '2-sec pause in the bottom stretch — this doubles as ankle mobility work for the duck-foot fix.',
          video: yt('standing calf raise form') },
        { id: 'abmachine',  name: 'Ab Crunch Machine',        sets: 2, reps: '12–15',   art: 'abmachine',  loc: 'Lifetime', core: true,
          tip: 'Exhale as you crunch, slow return. Weight you can control, not maximal.',
          video: yt('ab crunch machine form') },
        { id: 'sideplank',  name: 'Side Plank',               sets: 2, reps: '30s/side', art: 'sideplank', loc: 'Lifetime', core: true,
          tip: 'McGill staple for your back. Straight line ankle–hip–shoulder; don’t let the hip sag.',
          video: yt('side plank form') },
      ],
    },
    {
      id: 'oly',
      name: 'Oly + Explosive',
      where: 'Garage',
      icon: 'snatch',
      painTracked: true,
      warmup: true,
      exercises: [
        { id: 'drills',     name: 'Empty-Bar Snatch Drills',  sets: 1, reps: '5 min',   art: 'bar',        loc: 'Garage',
          tip: 'Snatch-grip RDL → high pull → muscle snatch → overhead squat, 5 reps each. This is the tune-up — don’t skip it.',
          video: yt('burgener warm up snatch') },
        { id: 'snatch',     name: 'Power Snatch',             sets: 6, reps: '2',       art: 'snatch',     loc: 'Garage',
          tip: 'Weeks 1–2 from the hang, weeks 3–4 from the floor. Crisp beats heavy every single week. Bar stays close, punch the lockout.',
          video: yt('power snatch technique') },
        { id: 'cleanjerk',  name: 'Power Clean + Push Jerk',  sets: 5, reps: '2+1',     art: 'cleanjerk',  loc: 'Garage',
          tip: 'Two cleans, one jerk per set. Bar speed is the judge — the moment it slows, stop adding weight.',
          video: yt('power clean push jerk technique') },
        { id: 'frontsquat', name: 'Front Squat',              sets: 3, reps: '3–5',     art: 'frontsquat', loc: 'Garage',
          tip: 'Light-moderate — position work, and it saves your legs for Saturday squats. Elbows high the whole rep.',
          video: yt('front squat form') },
        { id: 'boxjump',    name: 'Box / Broad Jump',         sets: 3, reps: '3',       art: 'boxjump',    loc: 'Garage',
          tip: 'Full recovery between sets — this is power, not conditioning. Land quiet like a cat.',
          video: yt('box jump technique') },
        { id: 'mcgill',     name: 'McGill Big-3 Circuit',     sets: 2, reps: '1 round', art: 'curlup',     loc: 'Garage', core: true,
          tip: 'Per round: bird dog ×8/side, side plank 30s/side, curl-up ×8. Done at home — no gym trip needed.',
          video: yt('McGill big 3 exercises') },
      ],
    },
  ],
};

// ── Weekly schedule ─────────────────────────────────────────────────────
// day: 0=Mon … 6=Sun
const SCHEDULE = {
  week1: [
    { day: 0, workout: 'push', label: 'Push', where: 'Lifetime' },
    { day: 1, workout: 'legs', label: 'Legs', where: 'Garage → Lifetime' },
    { day: 2, workout: 'pull', label: 'Pull', where: 'Lifetime' },
    { day: 3, workout: null,   label: 'Rest + ankle/hip mobility', where: 'Home' },
    { day: 4, workout: 'oly',  label: 'Oly + Explosive', where: 'Garage' },
    { day: 5, workout: null,   label: 'Optional zone-2 or full rest', where: '—' },
    { day: 6, workout: null,   label: 'Sunday mobility session', where: 'Home' },
  ],
  week2plus: [
    { day: 0, workout: 'push', label: 'Push', where: 'Lifetime' },
    { day: 1, workout: null,   label: 'Hockey (evening) — morning routine only', where: 'Rink' },
    { day: 2, workout: null,   label: 'Dryland + hockey — full day, nothing else', where: 'Rink' },
    { day: 3, workout: 'pull', label: 'Pull (daytime) + hockey (evening)', where: 'Lifetime' },
    { day: 4, workout: 'oly',  label: 'Oly + Explosive', where: 'Garage' },
    { day: 5, workout: 'legs', label: 'Legs', where: 'Garage → Lifetime' },
    { day: 6, workout: null,   label: 'Sunday mobility session', where: 'Home' },
  ],
};

const PROGRESSION = {
  1: { label: 'Week 1 — re-entry',
       upper: 'RPE 7, establish baselines, keep 2–3 reps in reserve.',
       lower: 'Deliberately easy: ~50–60% pre-injury squat. Log pain after every session.',
       oly:   'Hang power variations, technique weight only.' },
  2: { label: 'Week 2 — build',
       upper: '+5 lb or +1 rep per set (RPE 7–8).',
       lower: '+10–20 lb only if week 1 was pain-free.',
       oly:   'Lifts move to the floor, still light.' },
  3: { label: 'Week 3 — heaviest',
       upper: 'Heaviest week, RPE 8.',
       lower: '+10–20 lb again if the back stays quiet. Cap at RPE 8.',
       oly:   'Build to a crisp daily-max power snatch + power clean single — only if the back has been silent 2 straight weeks.' },
  4: { label: 'Week 4 — consolidate',
       upper: 'Repeat wk3 weights, move them faster — or cut volume 30% if run down.',
       lower: 'Hold wk3 weight and own it.',
       oly:   'If positions + back both feel good: test light full (squat) snatch and clean. The “I’m back” checkpoint.' },
};

const GUARDRAILS = [
  'Pain is the gate: 0–2/10 during a set → proceed. Anything sharper → drop weight or swap the variation that day.',
  'No grinding reps for these 4 weeks. You’re rebuilding the engine, not testing it.',
  'Squat substitutes, in order: box squat → tempo squat (3s down) → front squat → goblet squat.',
  'RDLs are patterning, not PRs. Form breaks = set over.',
  'Oly pulls stay at technique weight weeks 1–2 no matter how easy they feel.',
  'No heavy bending in the first ~30 min after waking — do the morning routine instead.',
];

const ROUTINES = [
  {
    id: 'warmup', name: 'Garage Lower-Body Warm-Up', when: 'Before every Legs + Oly session · ~6 min',
    items: [
      'Cat-cow × 10',
      'Ankle rocks (knee tracks over toes) × 10/side',
      'Glute bridge × 12 — 2-sec squeeze at top',
      'Dead bug × 8/side — low back pressed flat',
      'Bird dog × 6/side — 2-sec pause',
      'Bodyweight/goblet squat × 10, then ramp the bar up in 3s–5s',
    ],
  },
  {
    id: 'morning', name: 'Morning Routine', when: 'Every day · ~8 min · unsticks back + ankles',
    items: [
      'Cat-cow × 10 slow',
      'Ankle rocks, knee over toe × 10/side',
      'Half-kneeling hip flexor stretch — 30s/side, squeeze the back glute',
      'Glute bridge × 12 with 2-sec hold',
      'Bird dog × 6/side',
      'Supported deep squat hold (hold rack/doorframe) — 30s, heels down',
      'Standing overhead reach + side bend × 5/side',
    ],
  },
  {
    id: 'night', name: 'Night Routine', when: 'Every day · ~10 min · decompress + downshift',
    items: [
      'Knees-to-chest, gentle rock — 60s',
      'Figure-4 stretch — 45s/side',
      'Hamstring stretch w/ strap, leg up — 45s/side',
      'Reclined or regular pigeon — 60s/side',
      'Open-book T-spine rotation × 8/side',
      'Child’s pose — 90s, slow nasal breathing, long exhales',
    ],
  },
  {
    id: 'sunday', name: 'Sunday Mobility Session', when: 'Sundays · ~25 min · the duck-foot fixer',
    items: [
      'ANKLES — Wall calf stretch, straight knee — 60s/side',
      'ANKLES — Soleus stretch, bent knee — 60s/side',
      'ANKLES — Knee-over-toe ankle rocks × 15/side',
      'ANKLES — Tibialis raises (lean on wall, lift toes) — 2×15',
      'HIPS — 90/90 transitions × 10 slow',
      'HIPS — 90/90 internal-rotation lean — 45s/side',
      'HIPS — Adductor rockback × 10/side',
      'HIPS — Half-kneeling hip flexor stretch — 45s/side',
      'SPINE — Cat-cow × 10',
      'SPINE — Thread the needle × 8/side',
      'SPINE — Wall slides × 10',
      'SPINE — Lat stretch hanging off the rack — 45s',
      'FINISH — Deep squat hold 3×30s, breathe at the bottom',
      'FINISH — Bird dog × 8/side',
    ],
  },
];

const WALKING_CUE = 'Duck-foot walking cue: think “kneecaps point forward” and soften the knees. Don’t force the toes inward — the ankle + hip work is what actually changes it.';
